name: studyconnect

networks:
  studyconnect-network:
    external: true
    name: studyconnect-network

services:
  backend:
    image: sc-backend
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}-backend"
    environment:
      - BACKEND_API_URL=http://localhost:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ConnectionStrings__DefaultConnection=Server=mssql-server;Database=studyconnect;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - Entra__Instance=https://${TENANT_ID}.ciamlogin.com/
      - Entra__TenantId=${TENANT_ID}
      - Entra__ClientId=${CLIENT_ID}
      - Entra__Audience=api://${CLIENT_ID}
    ports:
      - "8080:8080"
    depends_on:
      mssql-server:
        condition: service_healthy
    networks:
      - studyconnect-network

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest # Or your desired version
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - studyconnect-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q \"SELECT 1\" -C"]
      interval: 10s
      timeout: 20s
      retries: 6