services:
  backend:
    image: sc-backend
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - BACKEND_API_URL=http://localhost:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
