// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyConnect.Data;

#nullable disable

namespace StudyConnect.Data.Migrations
{
    [DbContext(typeof(StudyConnectDbContext))]
    partial class StudyConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumCategory", b =>
                {
                    b.Property<Guid>("ForumCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ForumCategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ForumCategory", (string)null);

                    b.HasData(
                        new
                        {
                            ForumCategoryId = new Guid("a3f1d8a5-1b67-4a4f-91c1-9c63c2bde914"),
                            Description = "Software Entwicklung 2",
                            Name = "SWEN1"
                        },
                        new
                        {
                            ForumCategoryId = new Guid("e5b7f442-06c6-4d7e-b6fa-4f8f2420a6e7"),
                            Description = "Computer Technik 2",
                            Name = "CT-2"
                        },
                        new
                        {
                            ForumCategoryId = new Guid("c345e8a7-8c49-4326-83e7-2657b1d149f3"),
                            Description = "Betriebssysteme",
                            Name = "BSY"
                        },
                        new
                        {
                            ForumCategoryId = new Guid("a1b2c3d4-5678-4f90-abcd-1234567890ef"),
                            Description = "General Kontext",
                            Name = "General"
                        });
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumComment", b =>
                {
                    b.Property<Guid>("ForumCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ForumPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ForumCommentId");

                    b.HasIndex("ForumPostId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumComment", (string)null);
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumLike", b =>
                {
                    b.Property<Guid>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ForumCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ForumPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LikeId");

                    b.HasIndex("ForumCommentId");

                    b.HasIndex("ForumPostId");

                    b.HasIndex("UserId", "ForumPostId", "ForumCommentId")
                        .IsUnique()
                        .HasFilter("[ForumPostId] IS NOT NULL AND [ForumCommentId] IS NOT NULL");

                    b.ToTable("ForumLike", (string)null);
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumPost", b =>
                {
                    b.Property<Guid>("ForumPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ForumCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ForumPostId");

                    b.HasIndex("ForumCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumPost", (string)null);
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Visibility")
                        .HasColumnType("bit");

                    b.HasKey("GroupId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberId", "GroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MemberRoleId");

                    b.ToTable("GroupMember", (string)null);
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.MemberRole", b =>
                {
                    b.Property<Guid>("MemberRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MemberRoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MemberRole", (string)null);

                    b.HasData(
                        new
                        {
                            MemberRoleId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Is a member of a group",
                            Name = "GroupMember"
                        });
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.PostTag", b =>
                {
                    b.Property<Guid>("ForumPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ForumPostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTag", (string)null);
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            TagId = new Guid("dba25ed0-ea90-4de8-9b73-bedd16d15a5f"),
                            Description = "Ask your question here",
                            Name = "Question"
                        },
                        new
                        {
                            TagId = new Guid("27a0d0a6-9df8-429e-b473-129533d460d5"),
                            Description = "Looking for study group members",
                            Name = "Looking for Group"
                        },
                        new
                        {
                            TagId = new Guid("46fd2f68-df2d-4a0a-9137-f8556b4f132f"),
                            Description = "Discuss the topic here",
                            Name = "Discussion"
                        },
                        new
                        {
                            TagId = new Guid("9d2f3e3f-0f58-4d55-8337-84fecd2b84d3"),
                            Description = "Check existing problems or issues",
                            Name = "Issue"
                        });
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("URoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserGuid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("URoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("URoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("URoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            URoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Student is the default role with no rights.",
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumComment", b =>
                {
                    b.HasOne("StudyConnect.Data.Entities.ForumPost", "ForumPost")
                        .WithMany("ForumComments")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyConnect.Data.Entities.ForumComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyConnect.Data.Entities.User", "User")
                        .WithMany("ForumComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForumPost");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumLike", b =>
                {
                    b.HasOne("StudyConnect.Data.Entities.ForumComment", "ForumComment")
                        .WithMany("ForumLikes")
                        .HasForeignKey("ForumCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyConnect.Data.Entities.ForumPost", "ForumPost")
                        .WithMany("ForumLikes")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudyConnect.Data.Entities.User", "User")
                        .WithMany("ForumLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForumComment");

                    b.Navigation("ForumPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumPost", b =>
                {
                    b.HasOne("StudyConnect.Data.Entities.ForumCategory", "ForumCategory")
                        .WithMany("ForumPosts")
                        .HasForeignKey("ForumCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyConnect.Data.Entities.User", "User")
                        .WithMany("ForumPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.Group", b =>
                {
                    b.HasOne("StudyConnect.Data.Entities.User", "Owner")
                        .WithMany("Groups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.GroupMember", b =>
                {
                    b.HasOne("StudyConnect.Data.Entities.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyConnect.Data.Entities.User", "Member")
                        .WithMany("GroupMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyConnect.Data.Entities.MemberRole", "MemberRole")
                        .WithMany("GroupMembers")
                        .HasForeignKey("MemberRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Member");

                    b.Navigation("MemberRole");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.PostTag", b =>
                {
                    b.HasOne("StudyConnect.Data.Entities.ForumPost", "ForumPost")
                        .WithMany("PostTags")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyConnect.Data.Entities.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForumPost");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.User", b =>
                {
                    b.HasOne("StudyConnect.Data.Entities.UserRole", "URole")
                        .WithMany("Users")
                        .HasForeignKey("URoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("URole");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumCategory", b =>
                {
                    b.Navigation("ForumPosts");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumComment", b =>
                {
                    b.Navigation("ForumLikes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.ForumPost", b =>
                {
                    b.Navigation("ForumComments");

                    b.Navigation("ForumLikes");

                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.Group", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.MemberRole", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.Tag", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.User", b =>
                {
                    b.Navigation("ForumComments");

                    b.Navigation("ForumLikes");

                    b.Navigation("ForumPosts");

                    b.Navigation("GroupMembers");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("StudyConnect.Data.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
