# This is a basic workflow to help you get started with Actions

name: PR_review

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [ opened, reopened ]
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
    
        - name: Authenticate with GitHub CLI
          run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Add Reviewers
          run: gh pr edit "$PR_URL" --add-reviewer StudyConnect-ZHAW/back-end
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_URL: ${{ github.event.pull_request.html_url }}end
