name: PR_review

on:
  pull_request:
    types: [ opened, reopened ]
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
    
        - name: Authenticate with GitHub CLI
          run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Set Repository
          run: gh repo set-default "${{ github.repository }}"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Add Reviewers
          run: gh pr edit "${{ github.event.pull_request.html_url }}" --add-reviewer @StudyConnect-ZHAW/back-end
