name: Backend CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch: # enables manual trigger

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/studyconnect-zhaw/backend/staging:latest -f StudyConnect.API/Dockerfile .
          docker push ghcr.io/studyconnect-zhaw/backend/staging:latest

      - name: Clone StudyConnect-ZHAW GitOps repository
        run:
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/StudyConnect-ZHAW/StudyConnect.git gitops-repo

      - name: Update deployment manifest
        run: |
          sed -i 's|image: ghcr.io/studyconnect-zhaw/backend/staging:.*|image: ghcr.io/studyconnect-zhaw/backend/staging:latest|' gitops-repo/deployment/backend/K8s/staging/deployment.yaml

      - name: Commit and push changes
        run: |
          cd gitops-repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add deployment/backend/K8s/staging/deployment.yaml
          git commit -m "Update backend image"
          git push
        env: 
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Trigger Frontend Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'StudyConnect-ZHAW',
              repo: 'frontend',
              workflow_id: 'ci-cd-staging.yaml',
              ref: 'main'
            });