name: Cleanup SonarQube PR Projects

on:
  schedule:
    - cron: '0 2 * * *'  # Every night at 2 AM UTC
  workflow_dispatch:      # Also allow manual triggering
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch all PRs
        id: fetch_prs
        run: |
          gh pr list --state all --json number --repo ${{ github.repository }} > prs.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup SonarQube Projects for Closed PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          CLOSED_PRS=$(jq '.[] | select(.state != "OPEN") | .number' prs.json)
          for pr in $CLOSED_PRS; do
            projectKey="StudyConnect-pr-$pr"
            echo "Deleting SonarQube project: $projectKey"
            curl -X POST "$SONAR_HOST_URL/api/projects/delete?project=$projectKey" \
              -u "$SONAR_TOKEN:"
          done